### ISSUE TITLE
A modification request to hexo-theme-aircv

### ISSUE THREAD

**Issue by Jingqing3948** [rayspock/rayspock#1]
Hello! I am a cs major student. I recently found your Light version of hexo-theme-aircv while building my own personal website. After a few days of trying I really like this project as an online resume. But I wanted to modify it a little bit (because honestly, this project is the best hexo topic I've found so far on my online resume, but it's a little different from my own needs). I would also like to try to publish my modified version for other people to use (non-profit).

To be honest, I haven't done many releases like this before, so please forgive me if I have some questions. I wonder if you agree with me to do so? Do you need me to identify you as the original author of the project or any other information?

Thank you very much for your reply!

**Comment by Jingqing3948** [comment]
BTW, i also have another question. What advantages do you think the hexo cv theme have than some other frames such as academicpages? For me I only thought about its aesthetics and customization, because I think the most interesting part of my personal introduction is to include other parts besides academics.

(I brought this up mainly because I was thinking that if I were to introduce this project to other students, what reason would they have for choosing this topic over some academic personal website framework?)

(Here is my resume, still being modified:    [twjiang.cn](https://twjiang.cn)    )

**Comment by rayspock** [comment]
> Hello! I am a cs major student. I recently found your Light version of hexo-theme-aircv while building my own personal website. After a few days of trying I really like this project as an online resume. But I wanted to modify it a little bit (because honestly, this project is the best hexo topic I've found so far on my online resume, but it's a little different from my own needs). I would also like to try to publish my modified version for other people to use (non-profit).
> 
> To be honest, I haven't done many releases like this before, so please forgive me if I have some questions. I wonder if you agree with me to do so? Do you need me to identify you as the original author of the project or any other information?
> 
> Thank you very much for your reply!

Hi, thank you for your interest in the [hexo-theme-aircv](https://github.com/rayspock/hexo-theme-aircv) project. Please feel free to fork the project and tweak it as you wish as this project is no longer maintained.

**Comment by rayspock** [comment]
> BTW, i also have another question. What advantages do you think the hexo cv theme have than some other frames such as academicpages? For me I only thought about its aesthetics and customization, because I think the most interesting part of my personal introduction is to include other parts besides academics.
> 
> (I brought this up mainly because I was thinking that if I were to introduce this project to other students, what reason would they have for choosing this topic over some academic personal website framework?)
> 
> (Here is my resume, still being modified: [twjiang.cn](https://twjiang.cn) )

I have never used academicpages before, but it seems to be quite similar to hexo, except for the part where you have the flexibility to choose different themes like hexo does.  I have also switched to using [Hugo](https://gohugo.io/), which is much faster at generating websites as it's written in Go. Feel free to give it a Go!
